import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import { api } from "~/utils/api";
import type { ToastProps } from "react-toastify/dist/types";

function copyToClipboard(text: string) {
  navigator.clipboard.writeText(text).catch((err) => {
    console.error("Failed to copy: ", err);
  });
}

function isValidHttpUrl(string: string) {
  let url;
  try {
    url = new URL(string);
  } catch (_) {
    return false;
  }
  return url.protocol === "http:" || url.protocol === "https:";
}

const Home: NextPage = () => {
  const [url, setUrl] = useState("");
  const [slug, setSlug] = useState("");
  const [building, setBuilding] = useState(false);
  const [builtUrl, setBuiltUrl] = useState("");
  const originUrl = "slugz.ca";

  const { mutate: createSlug } = api.slug.build.useMutation({
    onSuccess: (data) => {
      setBuiltUrl(data);
      notify("Slug created!", "success");
      setSlug("");
      setUrl("");
      setBuilding(false);
      copyToClipboard(data);
    },
    onError: (error) => {
      notify(error.message, "error");
      setBuilding(false);
      setUrl("");
      setSlug("");
    }
  })

  const notify = (text: string, type: string) => {
    const props = {
      position: "bottom-right",
      autoClose: 5000,
      hideProgressBar: false,
      closeOnClick: true,
      pauseOnHover: true,
      draggable: true,
      progress: undefined,
      delay: 0,
    } as ToastProps;

    type === "error" ? toast.error(text, props) : toast.success(text, props);
  }
  const build = () => {
    setBuilding(true);

    if (!url || url === "") {
      notify("Please enter a URL!", "error");
      setBuilding(false);
      return;
    }

    if (!slug || slug === "") {
      notify("Please enter a slug!", "error");
      setBuilding(false);
      return;
    }

    if (!slug || !url || slug === "" || url === "") {
      notify("Please enter a slug and URL!", "error");
      setBuilding(false);
      return;
    }

    if (!isValidHttpUrl(url)) {
      notify("Please enter a valid URL!", "error");
      setBuilding(false);
      return;
    }
    
    // Create slug
    createSlug({
      url,
      slug
    })
  }

  return (
    <>
      <ToastContainer />

      <Head>
        <title>Slugz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Nav /> */}
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-80">
          <h1 className="hover:opacity-75 text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Slugz
          </h1>

          <p className="text-center">Build a slug given a URL. When you build a slug, it is shown to you below and automatically copied to your clipboard.</p>

          <form className="form-control min-w-full mb-16">
              <div>
                <label className="label">
                  <span className="label-text">Your URL</span>
                </label>
                <label className="input-group input-group-vertical">
                  <span className="pb-1">URL</span>
                  <input value={url} onChange={(e) => setUrl(e.target.value)} type="text" required placeholder="google.ca" className="input input-bordered" />
                </label>
              </div>

              <div className="mt-4">
                <label className="label">
                  <span className="label-text">Your Slug</span>
                </label>
                <label className="input-group input-group-vertical">
                  <span className="pb-1">Slug</span>
                  <input value={slug} onChange={(e) => setSlug(e.target.value)} type="text" required placeholder="Your slug (if one is not given, one will be provided)" className="input input-bordered" />
                </label>
              </div>

              <p className="mt-6 text-center">{originUrl}/{slug} <span className="text-green-400">points to:</span> {url}</p>

              <div className="mt-4">
                <button type="button" onClick={() => build()} className="btn w-full">
                  {building ? "Building..." : "Build"}
                </button>
              </div>

              {
                builtUrl && builtUrl !== "" ? (
                  <p className="mt-6 mb-24 text-center text-3xl">Your url: {builtUrl}</p>
                ) : null
              }
          </form>
        </div>
      </main>
    </>
  );
};

export default Home;